Repository PostHog/charts-clickhouse, pull requests merged in 2021-12, with the labels that each got.

#205 `clickhouse-operator`: upgrade to version 0.16.1
  .github/workflows/codespell.yaml
  charts/posthog/crds/clickhouse_installation_template.yaml
  charts/posthog/crds/clickhouse_operator_configurations.yaml
  charts/posthog/crds/clickhouseinstallations.clickhouse.altinity.com.yaml
  charts/posthog/crds/clickhouseinstallationtemplates.clickhouse.altinity.com.yaml
  charts/posthog/crds/clickhouseoperatorconfigurations.clickhouse.altinity.com.yaml
  charts/posthog/templates/clickhouse-operator/clusterrole.yaml
  charts/posthog/templates/clickhouse-operator/clusterrolebinding.yaml
  charts/posthog/templates/clickhouse-operator/configmap.yaml
  charts/posthog/templates/clickhouse-operator/deployment.yaml
  charts/posthog/templates/clickhouse-operator/service.yaml
  charts/posthog/templates/clickhouse-operator/serviceaccount.yaml
  charts/posthog/templates/clickhouse_cluster_role.yaml
  charts/posthog/tests/clickhouse-operator/__snapshot__/clusterrole.yaml.snap
  charts/posthog/tests/clickhouse-operator/__snapshot__/clusterrolebinding.yaml.snap
  charts/posthog/tests/clickhouse-operator/__snapshot__/configmap.yaml.snap
  charts/posthog/tests/clickhouse-operator/__snapshot__/deployment.yaml
  charts/posthog/tests/clickhouse-operator/__snapshot__/deployment.yaml.snap
  charts/posthog/tests/clickhouse-operator/__snapshot__/service.yaml
  charts/posthog/tests/clickhouse-operator/__snapshot__/service.yaml.snap
  charts/posthog/tests/clickhouse-operator/__snapshot__/serviceaccount.yaml
  charts/posthog/tests/clickhouse-operator/__snapshot__/serviceaccount.yaml.snap
  charts/posthog/tests/clickhouse-operator/clusterrole.yaml
  charts/posthog/tests/clickhouse-operator/clusterrolebinding.yaml
  charts/posthog/tests/clickhouse-operator/configmap.yaml
  charts/posthog/tests/clickhouse-operator/deployment.yaml
  charts/posthog/tests/clickhouse-operator/service.yaml
  charts/posthog/tests/clickhouse-operator/serviceaccount.yaml
  ci/k6-ingestion-test.js
  scripts/clickhouse_operator_sync.sh
Labels: bump major

#221 Dependency: `ingress-nginx` update from '3.25.0' to '4.0.13'
  charts/posthog/Chart.lock
  charts/posthog/Chart.yaml
  charts/posthog/charts/ingress-nginx-3.25.0.tgz
  charts/posthog/charts/ingress-nginx-4.0.13.tgz
  charts/posthog/templates/ingress.yaml
Labels: bump patch

#223 Dependency: `cert-manager` update from 1.2.0 to 1.6.1
  charts/posthog/Chart.lock
  charts/posthog/Chart.yaml
  charts/posthog/charts/cert-manager-v1.2.0.tgz
  charts/posthog/charts/cert-manager-v1.6.1.tgz
Labels: bump major

#213 Update Helm chart to support k8s 1.22
  .github/workflows/test-helm-chart.yaml
  charts/posthog/Chart.yaml
  charts/posthog/README.md
Labels: bump patch

#228 migrate: don't leave the job around after a failure
  charts/posthog/templates/migrate.job.yaml
Labels: bump patch

#230 Bump chart to PostHog v1.31.0
  charts/posthog/Chart.yaml
  charts/posthog/values.yaml
Labels: bump minor

#232 1.31.1 patch release
  charts/posthog/Chart.yaml
  charts/posthog/values.yaml
Labels: bump minor

#233 Fix typo in `charts/posthog/Chart.lock` :facepalm:
  charts/posthog/Chart.lock
  charts/posthog/Chart.yaml
Labels: bump minor
