Repository PostHog/charts-clickhouse, pull requests merged in 2022-05, with the labels that each got.

#364 Redis - upgrade bitnami/redis from 14.6.2 to 16.8.9
  charts/posthog/Chart.lock
  charts/posthog/Chart.yaml
  charts/posthog/charts/redis-14.6.2.tgz
  charts/posthog/charts/redis-16.8.9.tgz
Labels: bump major

#365 fix - fix for none being invalid email for letsencrypt
  charts/posthog/templates/cert-issuer.yaml
  charts/posthog/values.yaml
Labels: bump patch

#367 fix - index function does not pull nested keys separated by .
  charts/posthog/templates/cert-issuer.yaml
  charts/posthog/tests/cert-issuer.yaml
Labels: bump patch

#363 feat: Add redis memory policy
  charts/posthog/values.yaml
Labels: bump minor

#375 Zookeeper: don't scrape the metrics service
  charts/posthog/grafana-dashboards/zookeeper.json
  charts/posthog/tests/__snapshot__/grafana-dashboards.yaml.snap
  charts/posthog/values.yaml
Labels: bump patch

#376 clickhouse-operator: upgrade from 0.16.1 to 0.18.4
  charts/posthog/crds/clickhouseinstallations.clickhouse.altinity.com.yaml
  charts/posthog/crds/clickhouseinstallationtemplates.clickhouse.altinity.com.yaml
  charts/posthog/crds/clickhouseoperatorconfigurations.clickhouse.altinity.com.yaml
  charts/posthog/templates/clickhouse-operator/clusterrole.yaml
  charts/posthog/templates/clickhouse-operator/clusterrolebinding.yaml
  charts/posthog/templates/clickhouse-operator/configmap.yaml
  charts/posthog/templates/clickhouse-operator/deployment.yaml
  charts/posthog/templates/clickhouse-operator/service.yaml
  charts/posthog/templates/clickhouse-operator/serviceaccount.yaml
  charts/posthog/tests/clickhouse-operator/__snapshot__/clusterrole.yaml.snap
  charts/posthog/tests/clickhouse-operator/__snapshot__/clusterrolebinding.yaml.snap
  charts/posthog/tests/clickhouse-operator/__snapshot__/configmap.yaml.snap
  charts/posthog/tests/clickhouse-operator/__snapshot__/deployment.yaml.snap
  charts/posthog/tests/clickhouse-operator/__snapshot__/service.yaml.snap
  charts/posthog/tests/clickhouse-operator/__snapshot__/serviceaccount.yaml.snap
  charts/posthog/tests/clickhouse-operator/configmap.yaml
  charts/posthog/tests/clickhouse-operator/deployment.yaml
  charts/posthog/tests/clickhouse-operator/service.yaml
  charts/posthog/tests/clickhouse-operator/serviceaccount.yaml
  scripts/clickhouse_operator_sync.sh
Labels: bump major

#384 Set default/allow_nondeterministic_mutations to 1
  charts/posthog/tests/__snapshot__/clickhouse-instance.yaml.snap
  charts/posthog/tests/clickhouse-instance.yaml
  charts/posthog/values.yaml
Labels: bump patch

#377 Add security context to all deployments
  charts/posthog/templates/events-deployment.yaml
  charts/posthog/templates/pgbouncer-deployment.yaml
  charts/posthog/templates/plugins-deployment.yaml
  charts/posthog/templates/web-deployment.yaml
  charts/posthog/templates/worker-deployment.yaml
  charts/posthog/tests/events-deployment.yaml
  charts/posthog/tests/pgbouncer-deployment.yaml
  charts/posthog/tests/plugins-deployment.yaml
  charts/posthog/tests/web-deployment.yaml
  charts/posthog/tests/worker-deployment.yaml
  charts/posthog/values.yaml
Labels: bump patch

#341 chore(MinIO): add (optional) object storage service
  charts/posthog/Chart.lock
  charts/posthog/Chart.yaml
  charts/posthog/charts/minio-11.3.5.tgz
  charts/posthog/grafana-dashboards/minio.json
  charts/posthog/templates/_object_storage.tpl
  charts/posthog/templates/events-deployment.yaml
  charts/posthog/templates/migrate.job.yaml
  charts/posthog/templates/plugins-deployment.yaml
  charts/posthog/templates/web-deployment.yaml
  charts/posthog/templates/worker-deployment.yaml
  charts/posthog/tests/__snapshot__/grafana-dashboards.yaml.snap
  charts/posthog/tests/grafana-dashboards.yaml
  charts/posthog/tests/object-storage-settings.yaml
  charts/posthog/values.yaml
  ci/wait_for_all_the_posthog_resources_to_be_ready.sh
Labels: bump minor

#391 feat(objects-storage): Use `OBJECT_STORAGE_ENDPOINT` var
  charts/posthog/templates/_object_storage.tpl
  charts/posthog/tests/object-storage-settings.yaml
  charts/posthog/values.yaml
Labels: bump patch

#402 Bump app version to 1.36.0
  charts/posthog/ALL_VALUES.md
  charts/posthog/Chart.yaml
  charts/posthog/values.yaml
Labels: bump minor

#403 Dashboards - add NGINX
  charts/posthog/grafana-dashboards/nginx.json
  charts/posthog/tests/__snapshot__/grafana-dashboards.yaml.snap
  charts/posthog/tests/grafana-dashboards.yaml
Labels: bump patch
