Repository PostHog/charts-clickhouse, pull requests merged in 2022-08, with the labels that each got.

#500 PostHog release-1.38.0
  .devcontainer/devcontainer.json
  .devcontainer/setup_container.sh
  .github/workflows/test-amazon-web-services-install.yaml
  .github/workflows/test-google-cloud-platform-install.yaml
  charts/posthog/Chart.yaml
  charts/posthog/values.yaml
  ci/k6/ingestion-test.js
  ci/kubetest/conftest.py
  ci/setup_ingestion_test.sh
Labels: bump minor

#504 clickhouse-backup: bump default image from 1.4.0 to 1.5.0
  charts/posthog/values.yaml
Labels: bump patch

#505 Prometheus: add alerting rules for Redis
  charts/posthog/grafana-dashboards/redis.json
  charts/posthog/values.yaml
Labels: bump patch

#506 Use kubernetes existing secret for clickhouse password
  charts/posthog/ALL_VALUES.md
  charts/posthog/templates/_clickhouse.tpl
  charts/posthog/templates/clickhouse-backup-cronjob.yaml
  charts/posthog/templates/clickhouse_instance.yaml
  charts/posthog/tests/clickhouse-instance.yaml
  charts/posthog/values.yaml
Labels: bump minor

#508 values.yaml: add Grafana datasource for alertmanager
  charts/posthog/grafana-dashboards/clickhouse-overview.json
  charts/posthog/values.yaml
Labels: bump patch

#509 values.yaml: fix Grafana datasource for alertmanager
  charts/posthog/values.yaml
Labels: bump patch

#513 values.yaml: change prometheus alert rules output
  charts/posthog/values.yaml
Labels: bump patch

#514 values.yaml: tune not actionable prometheus alerts
  charts/posthog/values.yaml
Labels: bump patch

#515 chore(nginx): add path as a variable
  charts/posthog/grafana-dashboards/nginx.json
Labels: bump patch

#517 values.yaml: minor fixes to Prometheus alerts
  charts/posthog/values.yaml
Labels: bump patch

#518 values.yaml: dashboard + Prom alert iteration
  charts/posthog/grafana-dashboards/nginx.json
  charts/posthog/values.yaml
Labels: bump patch

#519 Helm: add Grafana annotations
  charts/posthog/templates/grafana-annotation-post.job.yaml
  charts/posthog/templates/grafana-annotation-pre.job.yaml
Labels: bump patch

#520 Revert "Helm: add Grafana annotations (#519)"
  charts/posthog/templates/grafana-annotation-post.job.yaml
  charts/posthog/templates/grafana-annotation-pre.job.yaml
Labels: bump patch

#521 Helm: add Grafana annotations (attempt #2)
  charts/posthog/templates/grafana-annotation-post.job.yaml
  charts/posthog/templates/grafana-annotation-pre.job.yaml
  charts/posthog/values.yaml
Labels: bump patch

#523 Grafana: add Helm deploy annotations to dashboards
  charts/posthog/grafana-dashboards/application-endpoints-overview.json
  charts/posthog/grafana-dashboards/clickhouse-overview.json
  charts/posthog/grafana-dashboards/kafka-overview.json
  charts/posthog/grafana-dashboards/kubernetes-deployment.json
  charts/posthog/grafana-dashboards/kubernetes-overview.json
  charts/posthog/grafana-dashboards/kubernetes-pvc.json
  charts/posthog/grafana-dashboards/minio.json
  charts/posthog/grafana-dashboards/nginx.json
  charts/posthog/grafana-dashboards/pgbouncer.json
  charts/posthog/grafana-dashboards/postgresql.json
  charts/posthog/grafana-dashboards/redis.json
  charts/posthog/grafana-dashboards/zookeeper.json
Labels: bump patch

#524 feat(nginx): parse logs as JSON with promtail
  .devcontainer/setup_container.sh
  .devcontainer/values.yml
  charts/posthog/values.yaml
Labels: bump patch

#526 fix(nginx): remove high card. fields from labels in promtail
  charts/posthog/values.yaml
Labels: bump patch

#527 chore: Bump version to 1.38.1
  charts/posthog/ALL_VALUES.md
  charts/posthog/Chart.yaml
  charts/posthog/values.yaml
Labels: bump minor

#528 feat(logging): use JSON formatted logs for Django code
  charts/posthog/templates/_posthog.tpl
  charts/posthog/values.yaml
Labels: bump patch

#529 fix(logging): use timestamp for Django logging extraction
  charts/posthog/values.yaml
Labels: bump patch

#525 Grafana: more dashboard improvements
  .github/workflows/codespell.yaml
  charts/posthog/grafana-dashboards/http-by-application-endpoint.json
Labels: bump patch

#533 Grafana: enhancement to the HTTP dashboard + Alertmanager config
  .github/workflows/codespell.yaml
  charts/posthog/grafana-dashboards/nginx.json
  charts/posthog/values.yaml
Labels: bump patch

#538 feat(logging): log Kubernetes with eventrouter
  .devcontainer/values.yml
  charts/posthog/templates/eventrouter.yaml
  charts/posthog/tests/eventrouter.yaml
  charts/posthog/values.yaml
Labels: bump patch

#532 fix(nginx): set service-upstream to "true"
  charts/posthog/values.yaml
Labels: bump minor

#541 feat(eventrouter): add resource config to eventrouter
  charts/posthog/templates/eventrouter.yaml
  charts/posthog/tests/eventrouter.yaml
  charts/posthog/values.yaml
Labels: bump patch

#543 fix(web): wait 10 seconds for k8s endpoints to be updated on term
  charts/posthog/templates/_snippet-web-deployments.tpl
  charts/posthog/templates/events-deployment.yaml
  charts/posthog/templates/web-deployment.yaml
  charts/posthog/tests/web-deployments.yaml
Labels: bump patch

#549 Revert "fix(nginx): set service-upstream to "true""
  charts/posthog/values.yaml
Labels: bump patch

#559 feat(grafana): add Dashboard for Gunicorn workers
  charts/posthog/grafana-dashboards/gunicorn-overview.json
Labels: bump patch

#561 chore(gunicorn): add missing deploy annotation
  charts/posthog/grafana-dashboards/gunicorn-overview.json
Labels: bump patch

#552 PostHog release-1.39.0
  charts/posthog/ALL_VALUES.md
  charts/posthog/Chart.yaml
  charts/posthog/values.yaml
  ci/values/amazon_web_services.yaml
  ci/values/digital_ocean.yaml
  ci/values/google_cloud_platform.yaml
  ci/values/k3s-plugin-server-split.yaml
  ci/values/k3s.yaml
Labels: bump minor, deploy

#565 feat(gunicorn): add http 502/504, cpu throttling, gunicorn criticals
  charts/posthog/grafana-dashboards/gunicorn-overview.json
Labels: bump patch

#564 Add nodeSelector and tolerations to hooks
  charts/posthog/ALL_VALUES.md
  charts/posthog/templates/migrate.job.yaml
  charts/posthog/tests/migrate-job.yaml
  charts/posthog/values.yaml
Labels: bump patch
