Repository PostHog/charts-clickhouse, pull requests merged in 2022-06, with the labels that each got.

#415 Add CLICKHOUSE_PORT as option for externalClickhouse configs
  charts/posthog/templates/_clickhouse.tpl
  charts/posthog/tests/__snapshot__/_clickhouse.tpl.yaml.snap
  charts/posthog/values.yaml
Labels: bump patch

#417 Revert "Add CLICKHOUSE_PORT as option for externalClickhouse configs"
  charts/posthog/templates/_clickhouse.tpl
  charts/posthog/tests/__snapshot__/_clickhouse.tpl.yaml.snap
  charts/posthog/values.yaml
Labels: bump patch

#419 Dashboards - add k8s
  charts/posthog/grafana-dashboards/kubernetes-overview.json
  charts/posthog/tests/__snapshot__/grafana-dashboards.yaml.snap
  charts/posthog/tests/grafana-dashboards.yaml
Labels: bump patch

#421 chore(k8s): remove 1.20 support, add 1.24
  .github/workflows/test-k6.yaml
  charts/posthog/Chart.yaml
  charts/posthog/README.md
Labels: bump major

#425 fix(CI): add bitnami_old repo
  .github/workflows/bump-version-workflow-dispatch.yaml
  .github/workflows/bump-version.yml
Labels: bump major

#431 feat: add ability to specify existing secret for Django SECRET_KEY
  charts/posthog/templates/_posthog.tpl
  charts/posthog/templates/_snippet-initContainers-wait-for-migrations.tpl
  charts/posthog/templates/events-deployment.yaml
  charts/posthog/templates/migrate.job.yaml
  charts/posthog/templates/plugins-deployment.yaml
  charts/posthog/templates/secrets.yaml
  charts/posthog/templates/web-deployment.yaml
  charts/posthog/templates/worker-deployment.yaml
  charts/posthog/tests/posthog-settings.yaml
  charts/posthog/values.yaml
Labels: bump minor

#430 Include site url in plugins deployment
  charts/posthog/templates/plugins-deployment.yaml
Labels: bump patch

#435 CI - cleanup Bitnami breaking change
  .github/workflows/bump-version-workflow-dispatch.yaml
  .github/workflows/bump-version.yml
  charts/posthog/Chart.lock
  charts/posthog/Chart.yaml
Labels: bump patch

#441 CH: externalZookeeper - fix indent
  charts/posthog/templates/clickhouse_instance.yaml
  charts/posthog/tests/clickhouse-instance.yaml
  charts/posthog/values.yaml
Labels: bump patch

#447 chore(hpa): update hpa apiVersion to autoscaling/v2beta2
  charts/posthog/templates/events-hpa.yaml
  charts/posthog/templates/pgbouncer-hpa.yaml
  charts/posthog/templates/plugins-hpa.yaml
  charts/posthog/templates/web-hpa.yaml
  charts/posthog/templates/worker-hpa.yaml
  charts/posthog/tests/events-hpa.yaml
  charts/posthog/tests/pgbouncer-hpa.yaml
  charts/posthog/tests/plugins-hpa.yaml
  charts/posthog/tests/web-hpa.yaml
  charts/posthog/tests/worker-hpa.yaml
Labels: bump minor

#451 Bump 1.37.0
  charts/posthog/ALL_VALUES.md
  charts/posthog/Chart.yaml
  charts/posthog/values.yaml
  ci/setup_ingestion_test.sh
  ci/values/k3s-plugin-server-split.yaml
Labels: bump minor

#450 feat(events): allow event pod resources to be set independently
  charts/posthog/templates/events-deployment.yaml
  charts/posthog/tests/events-deployment.yaml
Labels: bump minor

#453 fix(async): pass SITE_URL to plugins-async
  charts/posthog/templates/_posthog.tpl
  charts/posthog/templates/events-deployment.yaml
  charts/posthog/templates/migrate.job.yaml
  charts/posthog/templates/plugins-async-deployment.yaml
  charts/posthog/templates/plugins-deployment.yaml
  charts/posthog/templates/web-deployment.yaml
  charts/posthog/templates/worker-deployment.yaml
Labels: bump patch

#383 add backup cronjob
  charts/posthog/scripts/backup_script.sh
  charts/posthog/templates/_clickhouse.tpl
  charts/posthog/templates/clickhouse_backup_cronjob.yaml
  charts/posthog/templates/clickhouse_instance.yaml
  charts/posthog/templates/cronjob-backup-configmap.yaml
  charts/posthog/tests/clickhouse-instance.yaml
  charts/posthog/tests/cronjob-backup.yaml
  charts/posthog/values.yaml
  ci/kubetest/custom_k8s_resources/s3_minio.yaml
  ci/kubetest/test_clickhouse_backup.py
Labels: bump minor
