Repository PostHog/charts-clickhouse, pull requests merged in 2022-07, with the labels that each got.

#470 initContainer: CH service dependency
  charts/posthog/templates/_snippet-initContainers-wait-for-service-dependencies.tpl
Labels: bump patch

#474 chore: bump to 1.37.1
  charts/posthog/ALL_VALUES.md
  charts/posthog/Chart.yaml
  charts/posthog/values.yaml
Labels: bump minor

#475 Allow ImagePullPolicy configuration
  charts/posthog/templates/_snippet-initContainers-wait-for-migrations.tpl
  charts/posthog/templates/_snippet-initContainers-wait-for-service-dependencies.tpl
  charts/posthog/templates/clickhouse-backup-cronjob.yaml
  charts/posthog/templates/clickhouse_instance.yaml
  charts/posthog/templates/migrate.job.yaml
  charts/posthog/tests/__snapshot__/clickhouse-backup-cronjob.yaml.snap
  charts/posthog/values.yaml
Labels: bump minor

#473 PgBouncer - upgrade to 1.17.0
  charts/posthog/templates/pgbouncer-deployment.yaml
  charts/posthog/templates/pgbouncer-hpa.yaml
  charts/posthog/templates/pgbouncer-service.yaml
  charts/posthog/templates/plugins-hpa.yaml
  charts/posthog/tests/pgbouncer-hpa.yaml
  charts/posthog/values.yaml
  ci/kubetest/helpers/clickhouse.py
Labels: bump major

#477 PgBouncer - use pkill instead of killall
  charts/posthog/templates/pgbouncer-deployment.yaml
Labels: bump patch

#479 feat(pgbouncer): add Prometheus exporter as sidecar
  charts/posthog/templates/pgbouncer-deployment.yaml
  charts/posthog/values.yaml
  ci/kubetest/test_prometheus_pgbouncer_exporter.py
Labels: bump minor

#482 PgBouncer: fix resource regression
  charts/posthog/templates/pgbouncer-deployment.yaml
  charts/posthog/tests/__snapshot__/pgbouncer-deployment.yaml.snap
  charts/posthog/tests/pgbouncer-deployment.yaml
Labels: bump patch

#480 Grafana - add PgBouncer dashboards + minor fixes
  charts/posthog/grafana-dashboards/clickhouse-overview.json
  charts/posthog/grafana-dashboards/kubernetes-overview.json
  charts/posthog/grafana-dashboards/nginx.json
  charts/posthog/grafana-dashboards/pgbouncer.json
  charts/posthog/grafana-dashboards/postgresql.json
  charts/posthog/grafana-dashboards/redis.json
  charts/posthog/grafana-dashboards/zookeeper.json
  charts/posthog/tests/__snapshot__/grafana-dashboards.yaml.snap
  charts/posthog/tests/grafana-dashboards.yaml
Labels: bump patch

#486 Grafana: upgrade chart from 6.24.1 to 6.29.11
  charts/posthog/Chart.lock
  charts/posthog/Chart.yaml
  charts/posthog/charts/grafana-6.24.1.tgz
  charts/posthog/charts/grafana-6.29.11.tgz
Labels: bump patch

#488 Prometheus: alert KubernetesPodNotHealthy reporting incorrect alerts
  charts/posthog/values.yaml
Labels: bump patch

#490 Promtail&Prometheus: add default alerts
  charts/posthog/values.yaml
Labels: bump patch

#494 Grafana: add deployment dashboard + tweaks
  charts/posthog/grafana-dashboards/kubernetes-deployment.json
  charts/posthog/grafana-dashboards/kubernetes-overview.json
  charts/posthog/grafana-dashboards/kubernetes-pvc.json
  charts/posthog/grafana-dashboards/nginx.json
  charts/posthog/tests/grafana-dashboards.yaml
Labels: bump patch

#495 Dashboards: minor fixes
  charts/posthog/grafana-dashboards/kubernetes-deployment.json
  charts/posthog/grafana-dashboards/nginx.json
Labels: bump patch

#497 Make sentryDSN configurable for plugin server
  charts/posthog/templates/_posthog.tpl
  charts/posthog/templates/_snippet-initContainers-wait-for-migrations.tpl
  charts/posthog/templates/events-deployment.yaml
  charts/posthog/templates/migrate.job.yaml
  charts/posthog/templates/plugins-async-deployment.yaml
  charts/posthog/templates/plugins-deployment.yaml
  charts/posthog/templates/web-deployment.yaml
  charts/posthog/templates/worker-deployment.yaml
  charts/posthog/tests/events-deployment.yaml
  charts/posthog/tests/migrate-job.yaml
  charts/posthog/tests/plugins-async-deployment.yaml
  charts/posthog/tests/plugins-deployment.yaml
  charts/posthog/tests/web-deployment.yaml
  charts/posthog/tests/worker-deployment.yaml
  charts/posthog/values.yaml
Labels: bump patch

#498 initContainer - wait for migrations: add env
  charts/posthog/templates/_snippet-initContainers-wait-for-migrations.tpl
  charts/posthog/tests/_initContainers-wait-for-migrations.yaml
Labels: bump patch

#501 chore(web): expose Prometheus port on web container
  charts/posthog/templates/events-deployment.yaml
  charts/posthog/templates/web-deployment.yaml
  charts/posthog/values.yaml
Labels: bump minor
