Repository PostHog/charts-clickhouse, pull requests merged in 2022-01, with the labels that each got.

#184 Deprecate 'beat' deployment
  charts/posthog/templates/beat-deployment.yaml
  charts/posthog/templates/workers-deployment.yaml
  charts/posthog/values.yaml
Labels: bump major

#234 K8s: move supported version to >=1.20 <= 1.23
  .github/workflows/test-helm-chart.yaml
  charts/posthog/Chart.yaml
  charts/posthog/README.md
Labels: bump major

#240 Add 'enabled' flag for all services
  charts/posthog/templates/events-deployment.yaml
  charts/posthog/templates/events-hpa.yaml
  charts/posthog/templates/events-service.yaml
  charts/posthog/templates/migrate.job.yaml
  charts/posthog/templates/pgbouncer-deployment.yaml
  charts/posthog/templates/pgbouncer-hpa.yaml
  charts/posthog/templates/pgbouncer-service.yaml
  charts/posthog/templates/plugins-deployment.yaml
  charts/posthog/templates/plugins-hpa.yaml
  charts/posthog/templates/web-deployment.yaml
  charts/posthog/templates/web-hpa.yaml
  charts/posthog/templates/web-service.yaml
  charts/posthog/templates/worker-deployment.yaml
  charts/posthog/templates/worker-hpa.yaml
  charts/posthog/tests/events-deployment.yaml
  charts/posthog/tests/events-hpa.yaml
  charts/posthog/tests/events-service.yaml
  charts/posthog/tests/migrate-job.yaml
  charts/posthog/tests/pgbouncer-deployment.yaml
  charts/posthog/tests/pgbouncer-hpa.yaml
  charts/posthog/tests/pgbouncer-service.yaml
  charts/posthog/tests/plugins-deployment.yaml
  charts/posthog/tests/plugins-hpa.yaml
  charts/posthog/tests/web-deployment.yaml
  charts/posthog/tests/web-hpa.yaml
  charts/posthog/tests/web-service.yaml
  charts/posthog/tests/worker-deployment.yaml
  charts/posthog/tests/worker-hpa.yaml
  charts/posthog/values.yaml
Labels: bump minor

#224 Make StorageClass installation optional in AWS/GCP
  charts/posthog/templates/_helpers.tpl
  charts/posthog/templates/clickhouse-operator/clusterrole.yaml
  charts/posthog/templates/clickhouse-operator/clusterrolebinding.yaml
  charts/posthog/templates/clickhouse-operator/configmap.yaml
  charts/posthog/templates/clickhouse-operator/deployment.yaml
  charts/posthog/templates/clickhouse-operator/service.yaml
  charts/posthog/templates/clickhouse-operator/serviceaccount.yaml
  charts/posthog/templates/clickhouse_instance.yaml
  charts/posthog/templates/storage_class.yaml
  charts/posthog/tests/__snapshot__/clickhouse-instance.yaml.snap
  charts/posthog/tests/clickhouse-instance.yaml
  charts/posthog/tests/clickhouse-operator/clusterrole.yaml
  charts/posthog/tests/clickhouse-operator/clusterrolebinding.yaml
  charts/posthog/tests/clickhouse-operator/configmap.yaml
  charts/posthog/tests/clickhouse-operator/deployment.yaml
  charts/posthog/tests/clickhouse-operator/service.yaml
  charts/posthog/tests/clickhouse-operator/serviceaccount.yaml
  charts/posthog/values.yaml
  ci/kubetest/clickhouse_existing_claim.yaml
  ci/kubetest/test_clickhouse_persistence_disabled.py
  ci/kubetest/test_clickhouse_persistence_enabled.py
  ci/kubetest/test_clickhouse_persistence_enabled_existing_claim.py
  ci/kubetest/utils.py
  ci/values/amazon_web_services.yaml
  ci/values/digital_ocean.yaml
  ci/values/google_cloud_platform.yaml
  ci/values/k3s.yaml
  ci/values/kubetest/test_clickhouse_persistence_disabled.yaml
  ci/values/kubetest/test_clickhouse_persistence_enabled.yaml
  ci/values/kubetest/test_clickhouse_persistence_enabled_existing_claim.yaml
  scripts/clickhouse_operator_sync.sh
Labels: bump major, P1, helm

#179 Remove all the (possible) Helm annotations
  .github/workflows/test-amazon-web-services-install.yaml
  .github/workflows/test-digitalocean-install.yaml
  .github/workflows/test-google-cloud-platform-install.yaml
  .github/workflows/test-helm-chart.yaml
  charts/posthog/templates/_snippet-initContainers-wait-for-migrations.tpl
  charts/posthog/templates/_snippet-initContainers-wait-for-service-dependencies.tpl
  charts/posthog/templates/_snippet-metadata-annotations-common.tpl
  charts/posthog/templates/_snippet-metadata-labels-common.tpl
  charts/posthog/templates/cert-issuer.yaml
  charts/posthog/templates/events-deployment.yaml
  charts/posthog/templates/events-hpa.yaml
  charts/posthog/templates/events-service.yaml
  charts/posthog/templates/ingress.yaml
  charts/posthog/templates/kafka-service.yaml
  charts/posthog/templates/metrics-deployment.yaml
  charts/posthog/templates/metrics-prometheus.yaml
  charts/posthog/templates/metrics-service.yaml
  charts/posthog/templates/migrate.job.yaml
  charts/posthog/templates/pgbouncer-deployment.yaml
  charts/posthog/templates/pgbouncer-hpa.yaml
  charts/posthog/templates/pgbouncer-service.yaml
  charts/posthog/templates/plugins-deployment.yaml
  charts/posthog/templates/plugins-hpa.yaml
  charts/posthog/templates/secrets.yaml
  charts/posthog/templates/serviceaccount.yaml
  charts/posthog/templates/web-deployment.yaml
  charts/posthog/templates/web-hpa.yaml
  charts/posthog/templates/web-service.yaml
  charts/posthog/templates/worker-deployment.yaml
  charts/posthog/templates/worker-hpa.yaml
  charts/posthog/tests/ingress.yaml
  charts/posthog/tests/kafka-service.yaml
  charts/posthog/tests/migrate-job.yaml
  ci/values/k3s.yaml
Labels: bump major, P0, helm

#254 Fix web-hpa config
  charts/posthog/templates/web-hpa.yaml
Labels: bump patch

#257 Fix template defaults for ClickHouse
  charts/posthog/templates/clickhouse_instance.yaml
  charts/posthog/tests/__snapshot__/clickhouse-instance.yaml.snap
  charts/posthog/tests/clickhouse-instance.yaml
Labels: bump minor

#248 Redis - refactor ENV variables injection & secret management
  .github/workflows/test-kubetest.yaml
  charts/posthog/templates/_helpers.tpl
  charts/posthog/templates/_snippet-error-on-removed-values.tpl
  charts/posthog/templates/_snippet-initContainers-wait-for-migrations.tpl
  charts/posthog/templates/_snippet-redis-env.tpl
  charts/posthog/templates/error-on-removed-values.yaml
  charts/posthog/templates/events-deployment.yaml
  charts/posthog/templates/migrate.job.yaml
  charts/posthog/templates/plugins-deployment.yaml
  charts/posthog/templates/secrets-redis-external.yaml
  charts/posthog/templates/secrets.yaml
  charts/posthog/templates/web-deployment.yaml
  charts/posthog/templates/worker-deployment.yaml
  charts/posthog/values.yaml
  ci/kubetest/custom_k8s_resources/redis_external.yaml
  ci/kubetest/custom_k8s_resources/redis_external_with_existing_secret.yaml
  ci/kubetest/custom_k8s_resources/redis_external_with_password.yaml
  ci/kubetest/custom_k8s_resources/redis_internal_with_existing_secret.yaml
  ci/kubetest/test_placeholder.py
  ci/kubetest/test_redis_external.py
  ci/kubetest/test_redis_external_with_existing_secret.py
  ci/kubetest/test_redis_external_with_password.py
  ci/kubetest/test_redis_internal_with_existing_secret.py
  ci/kubetest/test_redis_internal_with_password.py
  ci/kubetest/utils.py
  ci/values/amazon_web_services.yaml
  ci/values/digital_ocean.yaml
  ci/values/google_cloud_platform.yaml
  ci/values/k3s.yaml
  ci/values/kubetest/test_clickhouse_persistence_disabled.yaml
  ci/values/kubetest/test_clickhouse_persistence_enabled.yaml
  ci/values/kubetest/test_clickhouse_persistence_enabled_existing_claim.yaml
  ci/values/kubetest/test_clickhouse_service_loadbalancer.yaml
  ci/values/kubetest/test_clickhouse_service_nodeport.yaml
  ci/values/kubetest/test_redis_external.yaml
  ci/values/kubetest/test_redis_external_with_existing_secret.yaml
  ci/values/kubetest/test_redis_external_with_password.yaml
  ci/values/kubetest/test_redis_internal_with_existing_secret.yaml
  ci/values/kubetest/test_redis_internal_with_password.yaml
Labels: bump major

#268 Allow passing custom clickhouse settings
  charts/posthog/templates/clickhouse_instance.yaml
  charts/posthog/tests/clickhouse-instance.yaml
  charts/posthog/values.yaml
  ci/kubetest/test_clickhouse_custom_settings_profile.py
  ci/kubetest/test_clickhouse_persistence_enabled_existing_claim.py
  ci/kubetest/utils.py
Labels: bump minor

#276 External clickhouse support
  .github/workflows/test-kubetest.yaml
  .github/workflows/test-unit-helm.yaml
  charts/posthog/README.md
  charts/posthog/templates/_clickhouse.tpl
  charts/posthog/templates/_helpers.tpl
  charts/posthog/templates/_snippet-error-on-removed-values.tpl
  charts/posthog/templates/_snippet-initContainers-wait-for-migrations.tpl
  charts/posthog/templates/clickhouse_instance.yaml
  charts/posthog/templates/events-deployment.yaml
  charts/posthog/templates/migrate.job.yaml
  charts/posthog/templates/plugins-deployment.yaml
  charts/posthog/templates/secrets-clickhouse-external.yaml
  charts/posthog/templates/test-templates/clickhouse-env.yaml
  charts/posthog/templates/web-deployment.yaml
  charts/posthog/templates/worker-deployment.yaml
  charts/posthog/tests/__snapshot__/_clickhouse.tpl.yaml.snap
  charts/posthog/tests/_clickhouse.tpl.yaml
  charts/posthog/tests/clickhouse-instance.yaml
  charts/posthog/values.yaml
  ci/kubetest/custom_k8s_resources/clickhouse_external_secret.yaml
  ci/kubetest/test_clickhouse_connectivity.py
  ci/kubetest/utils.py
  ct.yaml
Labels: bump major

#284 Release v1.32.0
  charts/posthog/Chart.yaml
  charts/posthog/values.yaml
Labels: bump minor
