Repository PostHog/charts-clickhouse, pull requests merged in 2022-02, with the labels that each got.

#286 fix(email): ensure email.existingSecretKey is used
  charts/posthog/templates/_email.tpl
  charts/posthog/templates/events-deployment.yaml
  charts/posthog/templates/migrate.job.yaml
  charts/posthog/templates/web-deployment.yaml
  charts/posthog/templates/worker-deployment.yaml
  charts/posthog/tests/email-settings.yaml
Labels: bump minor

#289 Monitoring: cleanup statsd service & config
  charts/posthog/Chart.lock
  charts/posthog/Chart.yaml
  charts/posthog/templates/_helpers.tpl
  charts/posthog/templates/_statsd.tpl
  charts/posthog/templates/events-deployment.yaml
  charts/posthog/templates/metrics-deployment.yaml
  charts/posthog/templates/metrics-prometheus.yaml
  charts/posthog/templates/metrics-service.yaml
  charts/posthog/templates/pgbouncer-deployment.yaml
  charts/posthog/templates/plugins-deployment.yaml
  charts/posthog/templates/test-templates.yaml
  charts/posthog/templates/web-deployment.yaml
  charts/posthog/templates/worker-deployment.yaml
  charts/posthog/tests/_statsd.yaml
  charts/posthog/tests/statsd-settings.yaml
  charts/posthog/values.yaml
  ci/kubetest/test_statsd_external.py
  ci/kubetest/utils.py
Labels: bump major

#222 Deprecate `clickhouseOperator.useNodeSelector`
  charts/posthog/templates/_snippet-error-on-removed-values.tpl
  charts/posthog/templates/clickhouse_instance.yaml
  charts/posthog/values.yaml
Labels: P2, helm

#294 Monitoring: add Grafana
  charts/posthog/Chart.lock
  charts/posthog/Chart.yaml
  charts/posthog/charts/grafana-6.21.2.tgz
  charts/posthog/grafana-dashboards/redis.json
  charts/posthog/templates/grafana-dashboards.yaml
  charts/posthog/tests/__snapshot__/grafana-dashboards.yaml.snap
  charts/posthog/tests/grafana-dashboards.yaml
  charts/posthog/values.yaml
  ci/kubetest/test_grafana.py
Labels: bump minor

#301 Make clickhouse version configurable
  charts/posthog/templates/_clickhouse.tpl
  charts/posthog/templates/clickhouse_instance.yaml
  charts/posthog/tests/clickhouse-instance.yaml
  charts/posthog/values.yaml
  ci/kubetest/helpers/__init__.py
  ci/kubetest/helpers/clickhouse.py
  ci/kubetest/helpers/metrics.py
  ci/kubetest/helpers/utils.py
  ci/kubetest/test_clickhouse_connectivity.py
  ci/kubetest/test_clickhouse_custom_settings_profile.py
  ci/kubetest/test_clickhouse_different_image.py
  ci/kubetest/test_clickhouse_persistence_disabled.py
  ci/kubetest/test_clickhouse_persistence_enabled.py
  ci/kubetest/test_clickhouse_persistence_enabled_existing_claim.py
  ci/kubetest/test_clickhouse_service_loadbalancer.py
  ci/kubetest/test_clickhouse_service_nodeport.py
  ci/kubetest/test_grafana.py
  ci/kubetest/test_postgresql_connectivity.py
  ci/kubetest/test_posthog_hpa_enabled.py
  ci/kubetest/test_prometheus_kafka_exporter.py
  ci/kubetest/test_prometheus_postgres_exporter.py
  ci/kubetest/test_prometheus_redis_exporter.py
  ci/kubetest/test_redis_external.py
  ci/kubetest/test_redis_external_with_existing_secret.py
  ci/kubetest/test_redis_external_with_password.py
  ci/kubetest/test_redis_internal_with_existing_secret.py
  ci/kubetest/test_redis_internal_with_password.py
  ci/kubetest/test_statsd_external.py
Labels: bump minor

#303 Fix bumping chart version
  .github/workflows/bump-version-workflow-dispatch.yaml
  .github/workflows/bump-version.yml
Labels: bump patch

#313 Kafka - fix for `externalKafka.brokers`
  charts/posthog/templates/_kafka.tpl
  charts/posthog/tests/kafka-settings.yaml
  charts/posthog/values.yaml
  ci/kubetest/test_kafka_external.py
Labels: bump major

#315 Release PostHog 1.33.0
  charts/posthog/Chart.yaml
  charts/posthog/values.yaml
  ci/k6/ingestion-test.js
Labels: bump minor
